### ISSUE TITLE
Error in gov.nasa.jpf.symbc.numeric.solvers.ProblemZ3 class

### ISSUE THREAD

**Issue by srgiri** [SymbolicPathFinder/jpf-symbc#12]
Hi,
   I am getting one error:

```java
java.lang.NumberFormatException: For input string: "0.0000000000?"
```

when using float and double as method arguments. 

I observed if I modify the line# 1120 in ProblemZ3 class 
form
```java
return Double.parseDouble(strResult); 
```
to
```java
 return Double.parseDouble(strResult.replace("?", "").trim());
```
then it works properly. Please check this issue.

Regards,
S R Giri

**Comment by corinus** [comment]
yes you are right. I will correct.
Corina

**Comment by corinus** [comment]
This error has been fixed.
Please check.
Thank you,
Corina

**Comment by srgiri** [comment]
Thank you.
