### ISSUE TITLE
Z3BitvectorIncremental error :: incorrect answer

### ISSUE THREAD

**Issue by JHTaljaard** [SymbolicPathFinder/jpf-symbc#14]
Hello,

When I run Z3BitvectorIncremental on an example such as WBS, I do not get the correct results. 

Here is the output on the WBS example for reference:
```
====================================================== statistics
elapsed time:       00:00:00
states:             new=1,visited=0,backtracked=1,end=1
search:             maxDepth=1,constraints=0
choice generators:  thread=1 (signal=0,lock=1,sharedRef=0,threadApi=0,reschedule=0), data=0
heap:               new=347,released=12,maxLive=0,gcCycles=1
instructions:       3564
max memory:         981MB
loaded code:        classes=60,methods=1280
====================================================== search finished
```

Hope you can help with this.
Thank you

**Comment by corinus** [comment]
Sorry for answering so late.
what is the configuration you are using?
you should use the following options for incremental solving::

symbolic.dp=z3inc
symbolic.optimizechoices=false
listener = gov.nasa.jpf.symbc.numeric.solvers.IncrementalListener

**Comment by JHTaljaard** [comment]
Hello,

Thank you for your reply and effort. 

My mistake, I initially forgot to add the details of the configuration, but here it is for clarification:
```
symbolic.method = WBS.launch(sym#sym#sym#sym#sym#sym#sym#sym#sym)
symbolic.min_int=-100000
symbolic.max_int=100000
symbolic.dp=z3bitvectorinc
search.multiple_errors=true
```

I see setting the command: _symbolic.optimizechoices=false_ makes a difference.
The program appears to be working now.

Thank you very much.
