### ISSUE TITLE
How to find Symbolic JPF doc

### ISSUE THREAD

**Issue by Kogmawzy** [SymbolicPathFinder/jpf-symbc#16]
I clicked the link http://babelfish.arc.nasa.gov/trac/jpf/wiki/projects/jpf-symbc/doc in order to get the document, however, the account and password are needed. So how can I get it ?

**Comment by corinus** [comment]
Let me update the Wiki page. I should be able to address this by the end of this week.

**Comment by Kogmawzy** [comment]
Thx a lot . A  case uising Geen solver would be more appreciated.

**Comment by corinus** [comment]
I copied the doc and you should be able to access it (on the wiki pages). It is old and needs to be updated.

**Comment by corinus** [comment]
Hi
I have updated the documentation on wiki.
