### ISSUE TITLE
test java container class

### ISSUE THREAD

**Issue by zjzh** [SymbolicPathFinder/jpf-symbc#2]
I read your wiki ,know SPF can do Test input generation for Java container classes,but I want to know how you generate test cases,can you recommand me a paper?
Thank you !

**Comment by corinus** [comment]
Hi:
You can start with these papers:

Willem Visser, Corina S. Pasareanu, Radek Pelánek:
Test input generation for java containers using state matching. ISSTA 2006: 37-48

Corina S. Pasareanu, Willem Visser, David H. Bushnell, Jaco Geldenhuys, Peter C. Mehlitz, Neha Rungta:
Symbolic PathFinder: integrating symbolic execution with model checking for Java bytecode analysis. Autom. Softw. Eng. 20(3): 391-425 (2013)

**Comment by zjzh** [comment]
@corinus Thanks for your reply.
I want to ask again,when SPF encounter container class API such as TreeSet.add(E e),how does it handle?

**Comment by corinus** [comment]
you can take a look at examples/sequences
