### ISSUE TITLE
Repositories sync - is it automated ?

### ISSUE THREAD

**Issue by grzesuav** [SymbolicPathFinder/jpf-symbc#28]
Hi, is sync between babelfish and this github repo automated ? Is there any way to know when sync was performed ?

**Comment by corinus** [comment]
Hi The version on babelfish is no longer supported.

**Comment by grzesuav** [comment]
@corinus what about https://babelfish.arc.nasa.gov/trac/jpf/wiki/projects/jpf-symbc ? Is mentioned in readme but actually cannot visit page without log in

**Comment by corinus** [comment]
all the code is on github. The Readme has been updated to avoid confusion.
