### ISSUE TITLE
Ant Build failed

### ISSUE THREAD

**Issue by BinduAvadhani** [SymbolicPathFinder/jpf-symbc#29]
Hello,
I am not able to build the symbc-master with ant.
At different line numbers of SymbolicInstructionFactory.java errors are found.
After built done the result is as follows.
jpf-symbc-master\src\main\gov\nasa\jpf\symbc\SymbolicInstructionFactory.java:406: error: cannot find symbol 
[javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 100 errors

BUILD FAILED

**Comment by letonchanh** [comment]
Hi, 
I also encountered this problem yesterday, then followed the instructions here https://verificationglasses.wordpress.com/2017/02/13/installing-java-pathfinder-jpf-for-symbolic-execution/, and it works. You need to install jpf-core first, the instruction is here https://github.com/javapathfinder/jpf-core/wiki/Build,-Test,-Run.

Note that you don't have to change the path of `JUNIT_HOME` in build.xml. Just need to add `export JUNIT_HOME=/path/to/junit` into your `~/.bashrc`.

**Comment by BinduAvadhani** [comment]
Hai,
I tried but still i am not able to build the jpf-symbc-master.
Please help me in this regard.
Regards,
Avadhani Bindu.

**Comment by corinus** [comment]
Hi:
May I ask if you were able to first install jpf-core?

**Comment by BinduAvadhani** [comment]
Hello..
Yes I am able to build the jpf core.
Regards
Avadhani bindu.

**Comment by BinduAvadhani** [comment]
Hello:
I am able to build the jpf-core using ant but
i am unable to build the jpf-core-master using gradle.
When i tried building jpf-core -master with the command "gradle buildJars
--info" it is as follows

*FAILURE: Build failed with an exception.*
** Where:*
*Build file 'C:\Users\Bindu Avadhani\JPF\jpf-core-master\build.gradle'
line: 25*
** What went wrong:*
*A problem occurred evaluating root project 'jpf-core'.*
*> Failed to apply plugin [id 'com.palantir.git-version']*
*   > Cannot find '.git' directory*

Kindly help me in building the jpf-core and jpf-symbc

Regards,
Avadhani Bindu

**Comment by violetbingzhe** [comment]
Hello,

I am trying to install the jpf-symbc, but I don't have access to the wiki page that is hosting under NASA (https://babelfish.arc.nasa.gov/trac/jpf/wiki/projects/jpf-symbc). Do you guys have an alternative installing instructions? Thanks!

**Comment by corinus** [comment]
the instructions are in the readme
