### ISSUE TITLE
some confusion about spf generating test cases.

### ISSUE THREAD

**Issue by idiomaticrefactoring** [SymbolicPathFinder/jpf-symbc#3]
Hi:
when I set  symbolic.method in *.jpf, it can generate PC constraints and test cases,But it only generate PC constraints include symbolic parameters, don't generate PC constraints  for others branches contained others local variables ,how can it guarantee Branch coverage?
Thank you!

**Comment by zjzh** [comment]
I guess maybe it based on Jpf-core to guarantee Branch coverage.
