### ISSUE TITLE
Match statement with constraints

### ISSUE THREAD

**Issue by dah-fari7009** [SymbolicPathFinder/jpf-symbc#38]
Good morning,

I was wondering iif there is a way to know which specific statement in a program generated a given path constraint in the path summaries obtained with Symbolic PathFinder ? Here I mean, 
let's say I have this bit of code :

![tesssttt](https://user-images.githubusercontent.com/35702512/71636036-c588ce00-2bdf-11ea-8361-61f60cc0e852.PNG)

I obtain a summary like (val > 2) && val = 3 V (val<=2) && val =2 
Is there a way for me to know during the symbolic execution that (val > 2) was obtained when parsing line 3 ?

Thanks !

**Comment by corinus** [comment]
The PCChoiceGenerator records that information (in method and offset)
