### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by dah-fari7009** [SymbolicPathFinder/jpf-symbc#40]
Hello,

I am running symbolic execution on an example and for some reason that I can't quite understand I get an ArithmeticException. My code looks like:

double test(double x,double y){
        double a = 3;
        double b = 5/(a*x); //Line 15 throwing the exception
        return b;
    }

Property Violated: PC is constraint # = 0
Property Violated: result is  "java.lang.ArithmeticException: division by zero..."
****************************

====================================================== error 1
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.ArithmeticException: division by zero
        at demo.instrumented.Iold.test(demo/instrumented/Iold.java:15)
        at demo.instrumented.Iold.main(demo/instrumented/Iold.java:40)

Since my values are all symbolic or non-zero, I don't understand why I am getting this exception.  Also, in my config file the min value for symbolic real numbers is 1, so symbolic execution should not test with x = 0

Would you mind sharing with me what might be causing this behavior ?

**Comment by corinus** [comment]
this is a bug. i will look into it. thank you.

**Comment by corinus** [comment]
can you share the configuration file?
the code in DDIV simply checks if the symbolic expression in the denominator can be zero.

**Comment by dah-fari7009** [comment]
Thank you !
Here is my config file 

target = demo.instrumented.Itest1
symbolic.method = demo.instrumented.Itest1.test(sym#sym)
classpath= /Users/farid/Desktop/Symbolic_Ex_Proj/2019_client_library_equivalence_checking/Implementation/target/classes
symbolic.min_int=-100 
symbolic.max_int=100 
symbolic.min_long=-100 
symbolic.max_long=100 
symbolic.min_real=1.0 
symbolic.max_real=10.0 
symbolic.debug = true 
symbolic.dp=z3 
search.depth_limit=5 
listener = gov.nasa.jpf.symbc.SymbolicListener 
search.multiple_errors=true

**Comment by dah-fari7009** [comment]
Does the symbolic execution engine take into consideration the values passed to the parameters in the main function ?
I mean do the values used in the DDIV class depend on the parameters given in main, even though the execution is not concolic ?

**Comment by dah-fari7009** [comment]
I also tried with a more complicated example:

public static double snippet (double psiC, double bank_ang) {
    double degToRad = 0.017453292519943295;
    double g = 68443.0;
    double rA = Math.pow(vA, 2.0) / Math.tan(bank_ang*degToRad) / g;
return rA;
}

And here, no matter what values I pass in the main I always get a division by zero exception

**Comment by corinus** [comment]
Hello there were some errors in DDIV.java that I corrected. Please pull and try again.
Also the input configuration shoudl specify min_double not min_real.
Thanks.

**Comment by dah-fari7009** [comment]
I understand, thank you very much !
