### ISSUE TITLE
README jpf-core download link not working

### ISSUE THREAD

**Issue by nkrishnasatvik** [SymbolicPathFinder/jpf-symbc#59]
I tried to download jpf-core through link https://github.com/yannicnoller/jpf-core/tree/0f2f2901cd0ae9833145c38fee57be03da90a64f given under Getting Started in the README file. But it doesn't seem to work.

Also, why is [this](https://github.com/javapathfinder/jpf-core) repository not used in place of the [current one](https://github.com/yannicnoller/jpf-core/tree/0f2f2901cd0ae9833145c38fee57be03da90a64f)?

My name is Krishna. I'm new to open source contributions. I wanted to contribute for a project under the JPF organization for GSOC'21.

So, please guide me and correct me if I make any mistakes along the way.

Thank you!

**Comment by corinus** [comment]
Hi
The link is still working:
https://github.com/yannicnoller/jpf-core/tree/0f2f2901cd0ae9833145c38fee57be03da90a64f
Can you please try.
Current SPF works with thsi older version of jpf-core.
Thanks.

**Comment by nkrishnasatvik** [comment]
Yes it's working now. I don't know what issue I was facing earlier.

Thanks @corinus!
