### ISSUE TITLE
How SPF generate test cases for symbolic arrays

### ISSUE THREAD

**Issue by woshazi** [SymbolicPathFinder/jpf-symbc#7]
Hello,
    I run SPF with examples arrays/Arrays.java,it can't generate values for sym arrays` int[] arr` such as new int[]{1,2,3} ,
	however it generate objectref. Can spf have any solutions to generate instance for symbolic arrays?
**For example:**

SPF generates  test cases such as:

```
@Test

	public void test5() {

		arrays_arrays.check_length(-1,[I@15b);

	}
```
```
 public static int check_length(int i, int[] arr) {
			arr[0]=0;
			int j = arr.length;
			int a = arr[1];
			int b = 10/j;
			if(arr[i]>0){
				System.out.println("yy");
			}
			return b;
		}
```		
	.jpf is: 
		target = arrays.Arrays
		symbolic.method=arrays.Arrays.check_length(sym#sym)
		search.multiple_errors=true
		symbolic.dp = z3
		symbolic.debug=on
		listener = .symbc.sequences.SymbolicSequenceListener

**Comment by woshazi** [comment]
I successfully solve it.

**Comment by Marvinmw** [comment]
hi, how do you solve it?
