### ISSUE TITLE
Get program Path constraint using Symbolic pathfinder

### ISSUE THREAD

**Issue by Alim9100** [SymbolicPathFinder/jpf-symbc#81]
Hello
I want to use this tool for getting path constraint of methods, But I want to choose methods in runtime. So I cannot write driver classes statically. Is there a way to choose methods or creating drivers dynamically?

**Comment by sohah** [comment]
Hi Ali,

You need to write something to get this information out. The path
constraint is collected during execution in the PathCondition class. One
way to perhaps do what you want is to update the SymbolicListener to filter
return instructions that belong to the methods of interest. Then you can
dump out the PathCondition of the thread at that point.


Soha

**Comment by Alim9100** [comment]
Hi,
Thanks for your response. Consider the example in the picture. I have two methods, Push and Pop. I execute different trace of these methods. for example Push pop, Push push pop pop,.... . So for each one, I need a driver similar to the picture. Each time I should change the body and parameters of test3 and main method and run the symbolic path finder to get PC. But I need a solution to get path condition without writing driver for each trace. because traces will create at runtime. Do you have any  idea? 
![1](https://github.com/SymbolicPathFinder/jpf-symbc/assets/59583087/ffa8309f-e185-4bff-8df0-d1eb21d30dcb)
![2](https://github.com/SymbolicPathFinder/jpf-symbc/assets/59583087/93c2e9c5-5909-4cd6-9f7b-aef1c372ffe7)

**Comment by sohah** [comment]
As I mentioned in my previous reply, you'd need to update SPF code to expose this information to the driver that you have. If you have any additional questions please contact us back.

@yannicnoller , I think we can close this issue now.
