### ISSUE TITLE
Resetting the symbolic values

### ISSUE THREAD

**Issue by karthiv** [SymbolicPathFinder/jpf-symbc#88]
Is there any way to reset the symbolic values along the path - chosen during execution?

If I have to model Input in a cycle, how to take different values of i - during each iteration?

while(true){
int i =  takeinput();
}

**Comment by yannicnoller** [comment]
Hi @karthiv! I am not sure whether I understand your issue correctly, but what you can do is to add new symbolic values at runtime, e.g.,

```
int N = 10;
int a[] = new int[N];
for (int i = 0; i < N; i++) {
   a[i] = Debug.makeSymbolicInteger("sym_" + i);
}
```

**Comment by karthiv** [comment]
Thank you so much for the response
