### ISSUE TITLE
How to get the constraints on symbolic output variables according to each path condition?

### ISSUE THREAD

**Issue by cervoliu** [SymbolicPathFinder/jpf-symbc#92]
By configuring the `.jpf` file one can specify the symbolic method and symbolic inputs. Some related (output) variables are then represented symbolically with symbolic inputs. 
How do I extract the constraints on symbolic outputs on each path condition? By the way, are there any resources (docs or manuals or etc.) that explain the source code of SPF? Thanks.

**Comment by sohah** [comment]
Hi @cervoliu,

To get the symbolic constraints on the output variables, you will have to extract them yourself from the `PathCondition` at the end of the execution path. 

There are some resources in the wiki. But you can also look at [this](https://javapathfinder.sourceforge.net/events/JPF-workshop-050108/SymbolicJPF08.pdf) presentation. It has some details about specific SPF-related architecture.

**Comment by sohah** [comment]
I am closing this issue, but you can open another one if you have any questions.

**Comment by sohah** [comment]
@yannicnoller, I think we can close this issue now.
